### ISSUE TITLE
"Language Codes" caused by the error

### ISSUE THREAD

**Issue by FanDean** [yizeng/jekyll-theme-simple-texture#4]
Hello, there is a bug here when I set `lang` to `zh` in the `_config.yml` file and then `Categories`, `Tags`, `Search`, `About` can not be displayed.

```yaml
# _config.yml
# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
#lang: en
lang: zh
...
```

![2017-07-07_22-27-07](https://user-images.githubusercontent.com/25637720/27962236-d8ff023e-6363-11e7-9ee6-612762e84a4c.png)

![2017-07-07_22-29-15](https://user-images.githubusercontent.com/25637720/27962261-f17626ee-6363-11e7-99c9-bbdec8745ae4.png)
